### ISSUE TITLE
Local Reports folders 

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#13]
Requirement : when we run a above feature file at that we get results in ./reports/qa/<unique_id (timestamp)>/ <unique id>/snapshots
can we save this as 
1. If Scenario Outline is present then 
     <unique id> as Scenario1_Example1/Scenario1_Example2/Scenario2_Example1
2. If Scenario is present then 
     <unique id> as Scenario1/Scenario2
3. In case of Multiple features 
     <unique id> as Feature1Scenario1_Example1/Feature1Scenario1_Example2/Feature1Scenario1_Example1/Feature1Scenario1_Example2

**Comment by SergeiZagriychuk** [comment]
New naming is available by default in 1.2-beta1 build.
It's not implemented completely as it mentioned in the ticket (because of technical complexity of such implementation) but folder name now contains of feature_name + scenario_name + example_num (if presents)
example_num is started showing when example number is greater than 1. so it's not added for the 1st example

if such implementation doesn't work for you please submit another ticket listing what should be improved in details.
but again due to high complexity and low importance it won't be taken into work with high priority
