### ISSUE TITLE
Examples for multiple scenarios run should get reset to 0

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#14]
Today I had done one test with one feature file containing multiple scenarios and each scenarios have multiple examples
Just to show you 
Abc.feature

Feature : f desc

Scenario outline: sc1 desc
GIVEN WHEN THEN
example
Row 1
Row 2

Scenario outline: sc2 desc
GIVEN WHEN THEN
example
Row 1
Row 2
Row 3

Scenario outline: sc3 desc
GIVEN WHEN THEN
example
Row 1
Row 2
Row 3
Row 4

Zebrunner output shows
f desc ( sc1 desc ) --> reset [L001]
f desc ( sc1 desc ) [L001]
f desc ( sc2 desc ) [L002]--> reset [L001]
f desc ( sc2 desc ) [L003]
f desc ( sc2 desc ) [L004]
f desc ( sc3 desc ) [L005]--> reset [L001]
f desc ( sc3 desc ) [L006]
f desc ( sc3 desc ) [L007]
f desc ( sc3 desc ) [L008]

Expected output :
1. If examples are there then first example should show [L001]
2. On change of scenario counter for example should reset to [L001]
3. In case of just scenario keyword no value should present as [L001].

**Comment by SergeiZagriychuk** [comment]
Fixed in 1.2-beta1 but with small limitation: example number is not shown for the first example in a row (the reason is technical complexity of implementation for current code base used)
No changes needed in test project.
If marking of the1st example is critical for you please submit a separate ticket for this.
