### ISSUE TITLE
Get warning for cucumber dependency

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-cucumber#2]
Hi,
When I try to run the script it gives me below error.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/prasad_shimpi/.m2/repository/info/cukes/cucumber-jvm-deps/1.0.5/cucumber-jvm-deps-1.0.5.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by SergeiZagriychuk** [comment]
@prasadjshimpi is this still actual for you with latest carina-cucumber release? 
Please provide more details on script which you're using here if so.

**Comment by SergeiZagriychuk** [comment]
Warning messages should be fixed in 1.2-beta1.
No additional updates needed in test project.

FYI To escape https://github.com/qaprosoft/carina/issues/1063 warning make sure not to extend CucumberRunner class by your Steps classes.
If you need driver instance there simply add "implements IDriverPool" for your Step class.
